export const bg: string;
export const buttonDefault: string;
export const cell: string;
export const hidden: string;
export const justifyCenter: string;
export const probeblock: string;
export const probeleft: string;
export const proberight: string;
export const title: string;
